# state population data 1790 (NHGIS)
# - we have sex data for whites, but not coloreds

library(tidyverse)

state_1790 <- 
  read_csv("data/1790/nhgis0028_ds1_1790_state.csv") %>% 
  as_tibble() %>%
  transmute(year = YEAR, state = STATE,
            
            # encoding scheme is gender_race_slavestatus_religion
            # we want specific data on race, gender, and slave status
            # we want cumulative data on white pop, colored pop, and slave pop
            
            male_white_NA_NA = AAP001, # white male population
            female_white_NA_NA = AAP002, # white female population
            NA_white_NA_NA = AAP001 + AAP002, # white population
            
            NA_nonwhite_free_NA = AAQ001, # free colored population
            NA_nonwhite_slave_NA = AAQ002, # slave colored population
            NA_nonwhite_NA_NA = AAQ001 + AAQ002 # colored population
            ) %>% 
  pivot_longer(cols = -c("state", "year"),
               names_to = c("sex", "race", "slave_status", "age"),
               names_sep = "_",
               values_to = "value") %>%
  transmute(country = "United States", 
            state,
            sex, 
            race,
            slave_status,
            age, 
            year = 1790, 
            statistic = "population",
            value,
            source = "INSERTSOURCENAMEHERE",
            notes = "generated by Prathik's R project here: https://github.com/prathikkantarajgowda/state",
            personentered = "Prathik", 
            complete = "yes")