# state population data 1840 (NHGIS)

library(tidyverse)

state_1840 <- 
  read_csv("data/1840/nhgis0034_ds7_1840_state.csv") %>% 
  as_tibble() %>%
  transmute(year = YEAR, state = STATE,
            
            # encoding scheme is gender_race_slavestatus_age
            # we want specific data on race, gender, and slave status
            # we want cumulative data on white pop, black pop, and slave pop
            male_white_NA_under5 = ACY001,
            male_white_NA_5to9 = ACY002,
            male_white_NA_10to14 = ACY003,
            male_white_NA_15to19 = ACY004,
            male_white_NA_20to29 = ACY005,
            male_white_NA_30to39 = ACY006,
            male_white_NA_40to49 = ACY007,
            male_white_NA_50to59 = ACY008,
            male_white_NA_60to69 = ACY009,
            male_white_NA_70to79 = ACY010,
            male_white_NA_80to89 = ACY011,
            male_white_NA_90to99 = ACY012,
            male_white_NA_100andover = ACY013,
            
            female_white_NA_under5 = ACY014,
            female_white_NA_5to9 = ACY015,
            female_white_NA_10to14 = ACY016,
            female_white_NA_15to19 = ACY017,
            female_white_NA_20to29 = ACY018,
            female_white_NA_30to39 = ACY019,
            female_white_NA_40to49 = ACY020,
            female_white_NA_50to59 = ACY021,
            female_white_NA_60to69 = ACY022,
            female_white_NA_70to79 = ACY023,
            female_white_NA_80to89 = ACY024,
            female_white_NA_90to99 = ACY025,
            female_white_NA_100andover = ACY026,
            
            male_black_free_under10 = ACZ001,
            male_black_free_10to23 = ACZ002,
            male_black_free_24to35 = ACZ003,
            male_black_free_36to54 = ACZ004,
            male_black_free_55to99 = ACZ005,
            male_black_free_100andover = ACZ006,
            
            female_black_free_under10 = ACZ007,
            female_black_free_10to23 = ACZ008,
            female_black_free_24to35 = ACZ009,
            female_black_free_36to54 = ACZ010,
            female_black_free_55to99 = ACZ011,
            female_black_free_100andover = ACZ012,
            
            male_black_slave_under10 = ACZ013,
            male_black_slave_10to23 = ACZ014,
            male_black_slave_24to35 = ACZ015,
            male_black_slave_36to54 = ACZ016,
            male_black_slave_55to99 = ACZ017,
            male_black_slave_100andover = ACZ018,
            
            female_black_slave_under10 = ACZ019,
            female_black_slave_10to23 = ACZ020,
            female_black_slave_24to35 = ACZ021,
            female_black_slave_36to54 = ACZ022,
            female_black_slave_55to99 = ACZ023,
            female_black_slave_100andover = ACZ024,
            
  ) %>% 
  pivot_longer(cols = -c("state", "year"),
               names_to = c("sex", "race", "slave_status", "age"),
               names_sep = "_",
               values_to = "value") %>%
  transmute(country = "United States", 
            state,
            sex, 
            race,
            slave_status,
            age, 
            year = 1840, 
            statistic = "population",
            value,
            source = "INSERTSOURCENAMEHERE",
            notes = "generated by Prathik's R project here: https://github.com/prathikkantarajgowda/state",
            personentered = "Prathik", 
            complete = "yes")
