# state population data 1890 (NHGIS)

library(tidyverse)

state_1890 <- 
  read_csv("data/1890/nhgis0047_ds27_1890_state.csv") %>% 
  as_tibble() %>%
  transmute(year = YEAR, state = STATE,
            
            # encoding scheme is gender_race_slavestatus_age
            # we want specific data on race, gender, and slave status
            # we want cumulative data on white pop, black pop, and slave pop
            
            male_white_NA_NA = AV0001 + AV0003 + AV0005,
            female_white_NA_NA = AV0002 + AV0004 + AV0006,
            male_black_NA_NA = AV0007,
            female_black_NA_NA = AV0008,
  ) %>% 
  pivot_longer(cols = -c("state", "year"),
               names_to = c("sex", "race", "slave_status", "age"),
               names_sep = "_",
               values_to = "value") %>%
  transmute(country = "United States", 
            state,
            sex, 
            race,
            slave_status,
            age, 
            year = 1890,
            statistic = "population",
            value,
            source = "NHGIS2021;",
            notes = "generated by Prathik's R project here: https://github.com/prathikkantarajgowda/state",
            personentered = "Prathik", 
            complete = "")
