# state population data 1900 (ICPSR 02896)
# race x sex (FOR WHITES, COLOREDS, blackS)

library(tidyverse)
library(haven)

state_1900 <- 
  read_dta("data/1900/DS0020/02896-0020-Data.dta") %>% 
  as_tibble() %>% 
  filter(level == 2) %>% 
  transmute(name,
          # race x sex (ONLY FOR WHITES, COLOREDS, blackS)
          # note: colored here is NOT short for black people. it includes
          # black, chinese, japanese, and native
          male_white_NA_NA = fbwmtot + nbwmnp + nbwmfp,
          female_white_NA_NA = fbwftot + nbwfnp + nbwffp,
          male_black_NA_NA = negmtot,
          female_black_NA_NA = negftot,
) %>% 
  pivot_longer(cols = -c(name),
               names_to = c("sex", "race", "slave_status", "age"),
               names_sep = "_",
               values_to = "value") %>% 
  transmute(country = "United States", 
            state = name,
            sex,
            race,
            slave_status,
            age,
            year = 1900,
            statistic = "population",
            value,
            source = "Haines2010;",
            notes = "generated by Prathik's R project here: https://github.com/prathikkantarajgowda/state",
            personentered = "Prathik", 
            complete = "yes")