# state population data 1940 (NHGIS)
# race x sex x age is finished (ONLY FOR WHITES, blackS, AND OTHER)

library(tidyverse)

state_1940 <- 
  read_csv("data/1940/nhgis0038_ds77_1940_state.csv") %>% 
  as_tibble() %>%
  mutate(year = YEAR, state = STATE) %>% 
  pivot_longer(cols = starts_with("BV1"),
               names_to = "demographic") %>%
  mutate(demographic = (parse_number(demographic)) - 1000,
         mod = demographic %% 16) %>% 
  transmute(country = "United States", 
            state,
            sex = ifelse(between(demographic, 1, 16) |
                              between(demographic, 33, 48) |
                              between(demographic, 65, 80),
                            "male", "female"),
            race = ifelse(between(demographic, 1, 32), "white",
                          ifelse(between(demographic, 33, 64), 
                                 "black", "other")),
            slave_status = "NA",
            age = case_when(mod == 0 ~ "75_and_over",
                            mod == 1 ~ "0_to_4",
                            mod == 2 ~ "5_to_0",
                            mod == 3 ~ "10_to_14",
                            mod == 4 ~ "15_to_19",
                            mod == 5 ~ "20_to_24",
                            mod == 6 ~ "25_to_29",
                            mod == 7 ~ "30_to_34",
                            mod == 8 ~ "35_to_39",
                            mod == 9 ~ "40_to_44",
                            mod == 10 ~ "45_to_49",
                            mod == 11 ~ "50_to_54",
                            mod == 12 ~ "55_to_59",
                            mod == 13 ~ "60_to_64",
                            mod == 14 ~ "65_to_69",
                            mod == 15 ~ "70_to_74"),
            year = 1940,
            statistic = "population",
            value,
            source = "INSERTSOURCENAMEHERE",
            notes = "generated by Prathik's R project here: https://github.com/prathikkantarajgowda/state",
            personentered = "Prathik", 
            complete = "")