# state population data 1950 (NHGIS)
# race x sex done

library(tidyverse)

state_1950 <- 
  read_csv("data/1950/nhgis0043_ds84_1950_state.csv") %>% 
  as_tibble() %>%
  transmute(year = YEAR, state = STATE,
            # encoding scheme is gender_race_slavestatus_age
            # we want specific data on race, gender, and slave status
            # we want cumulative data on white pop, colored pop, and slave pop
            male_white_NA_NA = B3P001 + B3P002,
            male_black_NA_NA = B3P003,
            male_nonwhiteorblack_NA_NA = B3P004,
            female_white_NA_NA = B3P005 + B3P006,
            female_black_NA_NA = B3P007,
            female_nonwhiteorblack_NA_NA = B3P008
            
  ) %>% 
  pivot_longer(cols = -c("state", "year"),
               names_to = c("sex", "race", "slave_status", "age"),
               names_sep = "_",
               values_to = "value") %>%
  transmute(country = "United States", 
            state,
            sex, 
            race,
            slave_status,
            age, 
            year = 1950, 
            statistic = "population",
            value,
            source = "INSERTSOURCENAMEHERE",
            notes = "generated by Prathik's R project here: https://github.com/prathikkantarajgowda/state",
            personentered = "Prathik", 
            complete = "yes")