# state population data 1960 (NHGIS)
# - no data on black people (only "white" and "non_white" here?)

library(tidyverse)

state_1960 <- 
  read_csv("data/1960/nhgis0044_ds91_1960_state.csv") %>% 
  as_tibble() %>%
  transmute(year = YEAR, state = STATE,
            # encoding scheme is gender_race_slavestatus_age
            # we want specific data on race, gender, and slave status
            # we want cumulative data on white pop, colored pop, and slave pop
            male_white_NA_NA = B5S001,
            male_black_NA_NA = B5S002,
            male_native_NA_NA = B5S003,
            male_japanese_NA_NA = B5S004,
            male_chinese_NA_NA = B5S005,
            male_filipino_NA_NA = B5S006,
            male_other_NA_NA = B5S007,
            
            female_white_NA_NA = B5S008,
            female_black_NA_NA = B5S009,
            female_native_NA_NA = B5S010,
            female_japanese_NA_NA = B5S011,
            female_chinese_NA_NA = B5S012,
            female_filipino_NA_NA = B5S013,
            female_other_NA_NA = B5S014
            
  ) %>% 
  pivot_longer(cols = -c("state", "year"),
               names_to = c("sex", "race", "slave_status", "age"),
               names_sep = "_",
               values_to = "value") %>%
  transmute(country = "United States", 
            state,
            sex, 
            race,
            slave_status,
            age, 
            year = 1960, 
            statistic = "population",
            value,
            source = "INSERTSOURCENAMEHERE",
            notes = "generated by Prathik's R project here: https://github.com/prathikkantarajgowda/state",
            personentered = "Prathik", 
            complete = "yes")