# state population data 1960 (NHGIS)
# - no data on black people (only "white" and "non_white" here?)

library(tidyverse)

state_1960 <- 
  read_csv("data/1960/nhgis0038_ds89_1960_state.csv") %>% 
  as_tibble() %>%
  mutate(year = YEAR, state = STATE) %>% 
  pivot_longer(cols = starts_with("B49"),
               names_to = "demographic") %>%
  mutate(demographic = (parse_number(substr(demographic, 4, 6))),
         mod = demographic %% 18) %>% 
  transmute(country = "United States", 
            state,
            sex = ifelse(between(demographic, 1, 18) |
                              between(demographic, 37, 54),
                            "male", "female"),
            race = ifelse(between(demographic, 1, 36), "white", "nonwhite"),
            slave_status = "NA",
            age = case_when(mod == 0 ~ "85_and_over",
                            mod == 1 ~ "0_to_4",
                            mod == 2 ~ "5_to_10",
                            mod == 3 ~ "10_to_14",
                            mod == 4 ~ "15_to_19",
                            mod == 5 ~ "20_to_24",
                            mod == 6 ~ "25_to_29",
                            mod == 7 ~ "30_to_34",
                            mod == 8 ~ "35_to_39",
                            mod == 9 ~ "40_to_44",
                            mod == 10 ~ "45_to_49",
                            mod == 11 ~ "50_to_54",
                            mod == 12 ~ "55_to_59",
                            mod == 13 ~ "60_to_64",
                            mod == 14 ~ "65_to_69",
                            mod == 15 ~ "70_to_74",
                            mod == 16 ~ "75_to_79",
                            mod == 17 ~ "80_to_84"),
            year = 1960,
            statistic = "population",
            value,
            source = "INSERTSOURCENAMEHERE",
            notes = "generated by Prathik's R project here: https://github.com/prathikkantarajgowda/state",
            personentered = "Prathik", 
            complete = "")